apply plugin: 'com.android.application'

android {
    namespace = "com.AuroraByteSoftware.AuroraDMX"
    signingConfigs {
    }
    compileSdk 37
    defaultConfig {
        applicationId "com.AuroraByteSoftware.AuroraDMX"
        minSdkVersion 23
        targetSdkVersion 37
        versionCode 70
        versionName '4.8.0'
    }
    buildTypes {
        release {
            // Enables code shrinking, obfuscation, and optimization for only
            // your project's release build type.
            // Breaks loading backup files because objects change names
            //minifyEnabled true

            // Enables resource shrinking, which is performed by the
            // Android Gradle plugin.
            //shrinkResources true

            // Includes the default ProGuard rules files that are packaged with
            // the Android Gradle plugin. To learn more, go to the section about
            // R8 configuration files.
            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'),
                    'proguard-rules.pro'

            ndk {
                debugSymbolLevel = 'FULL'
            }
        }
    }
    productFlavors {
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    namespace = 'com.AuroraByteSoftware.AuroraDMX'
    buildFeatures {
        buildConfig true
    }
    buildToolsVersion '36.1.0'
    compileSdkMinor 0
}

dependencies {
    implementation libs.commons.lang3
    //  from  https://dl.google.com/dl/android/maven2/index.html
    implementation libs.billing
    implementation libs.legacy.support.v13
    implementation libs.holocolorpicker
    implementation libs.annotation

    testImplementation libs.junit
    // Required for instrumented tests
    androidTestImplementation libs.annotation
    androidTestImplementation libs.ext.junit

    // Font awesome v4.5
    implementation libs.draglinearlayout
    implementation libs.android.iconify.fontawesome
    implementation libs.recyclerview
    implementation libs.preference
    implementation libs.appcompat

    // ArtNetStack as local module
    implementation project(':ArtNetStack')
}